In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [6]:
data={"color":["red","blue","green","yellow","purple"]}
df=pd.DataFrame(data)
df.head()

    color
0     red
1    blue
2   green
3  yellow
4  purple

In [8]:
label_encoder=LabelEncoder()
df["Color_label"]=label_encoder.fit_transform(df["color"])
df.head()

    color  Color_label
0     red            3
1    blue            0
2   green            1
3  yellow            4
4  purple            2

In [10]:
one_hot_encoding=OneHotEncoder(sparse_output=False)
color_encoded=one_hot_encoding.fit_transform(df[["color"]])
color_encoded_df=pd.DataFrame(color_encoded,columns=one_hot_encoding.get_feature_names_out(["color"]))
df=pd.concat([df,color_encoded_df],axis=1)
df.head()

,color,Color_label,color_blue,color_green,color_purple,color_red,color_yellow
0,red,3,0.0,0.0,0.0,1.0,0.0
1,blue,0,1.0,0.0,0.0,0.0,0.0
2,green,1,0.0,1.0,0.0,0.0,0.0
3,yellow,4,0.0,0.0,0.0,0.0,1.0
4,purple,2,0.0,0.0,1.0,0.0,0.0